server:
  port: 10010
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos地址
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
          filters: #给userservice添加过滤器
            - AddRequestHeader=who,jiangxf
            - AddRequestHeader=who1,jxf
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
      default-filters: #给所有服务添加过滤器
        - AddRequestHeader=Truth,Itcast is freaking awesome!
        - AddRequestHeader=False,Itcast is not freaking awesome!
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':  #"/**"表示允许跨域访问的资源
            allowedOrigins: # 允许哪些网站的跨域请求(跨域允许来源)
              - "http://127.0.0.1:5500"
              - "http://www.leyou.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

